---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on ubuntu ansible nodes.   
    apt: 
      name: apache2 
      state: present   
    when: ansible_os_family == "Debian"

  - name: install webserver on RedHat ansible nodes.   
    yum: 
      name: httpd 
      state: present   
    when: ansible_os_family =="RedHat"

